# site properties and page defaults
title: Steven R. Schofield Research Group
subtitle: University College London (UCL)
description: The Schofield Group at UCL, led by Professor Steven R. Schofield, studies quantum nanoscience using scanning tunnelling microscopy and related techniques.
show-title: true
show-subtitle: true
header: images/background.jpg
footer: images/background.jpg
header-dark: true
footer-dark: true

proofer: false

# site social media and other links
links:
  email: s.schofield@ucl.ac.uk
  orcid: 0000-0002-0727-3015
  google-scholar: -wb-YDkAAAAJ
  github: srschofield
  linkedin: steven-schofield
  address: /contact/
#  external: https://profiles.ucl.ac.uk/11379-steven-r-schofield
#  twitter: schofield-lab
#  youtube: schofield-lab

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
