- id: doi:10.1088/1361-648X/ae0be1
  type: paper
  image: /images/publications/ae0be1.gif

- id: doi:10.1021/acs.nanolett.5c02675
  type: paper
  description: This paper presents the first STM imaging and spectroscopy of hydrogenic acceptor wave functions in silicon, with effective-mass and tight-binding theory confirming their square-ring-like symmetry and acceptor character.
  image: /images/publications/images_large_nl5c02675_0004.jpg

- id: doi:10.1002/adma.202312282
  type: paper
  description: This work demonstrates deterministic placement of single arsenic dopants in silicon with 97 ± 2% yield, advancing the scalable assembly of atomically precise quantum devices.
  image: /images/publications/adma202312282-fig-0001-m.jpg

- id: doi:10.1038/ncomms2679
  type: paper
  description: This paper reports the unanticipated discovery of a new atomic-scale quantum dot state in silicon, created by atomic manipulation on a hydrogen-terminated surface, providing key insights into atomic-scale quantum dot behaviour.
  date: 2013-04-03
  image: /images/publications/41467_2013_Article_BFncomms2679_Fig6_HTML.jpg

- id: doi:10.1002/anie.202213982
  type: paper
  description: This paper reports that arsenic incorporates into Ge(001) at room temperature, addressing a key challenge for scalable donor-based quantum devices.
  image: /images/publications/anie202213982-toc-0001-m.jpg

- id: doi:10.1002/advs.202302101
  type: paper
  description: This study demonstrates, for the first time, a non-destructive method to probe two-dimensional electron liquids in silicon, revealing their properties—including quantum confinement thickness—and showcasing the thinnest technological electron liquid to date (0.45 nm).
  image: /images/publications/advs6137-fig-0003-m.jpg

- id: doi:10.1021/acs.nanolett.1c00677
  type: paper
  description: This paper reports the first observation of a charge density wave ground state in a semiconducting transition metal dichalcogenide, providing new insight into CDW formation mechanisms.
  image: /images/publications/images_large_nl1c00677_0005.jpg

- id: doi:10.1103/PhysRevLett.91.136104
  type: paper
  description: This seminal paper presents the first demonstration of atomically precise dopant placement in a semiconductor, laying the foundation for modern atomic-scale quantum electronic devices.
  image: /images/publications/PRL_schofield_2003.png

- id: doi:10.1088/2399-1984/ada901
  type: paper
  image: /images/publications/nanofada901f15_lr.jpg
  description: This roadmap reviews 25 years of progress since Kane’s proposal for donor-based qubits in silicon, charting advances, challenges, and future directions in atomic-scale semiconductor quantum technologies.

- id: doi:10.1038/s41467-024-44790-6
  type: paper
  description: This work demonstrates resist-free EUV-induced hydrogen desorption on Si(001):H, bridging atomic-precision STM lithography with scalable semiconductor manufacturing techniques.
  image: /images/publications/41467_2024_44790_Fig5_HTML.png.webp

- id: doi:10.1021/acs.jpcc.3c03916
  type: paper
  image: /images/publications/images_large_jp3c03916_0006.jpeg

- id:  doi:10.1126/sciadv.adf5997
  type: paper
  image: /images/publications/sciadv.adf5997-f1.jpg

- id: doi:10.1063/5.0145772
  type: paper
  image: /images/publications/151601_1_5.0145772.figures.online.f2.jpg

- id: doi:10.1021/acs.jpcc.1c07115
  type: paper
  image: /images/publications/jp1c07115_0005.webp

- id: doi:10.1088/1361-648X/abe6dd
  type: paper
  image: /images/publications/cmabe6ddf2_online.jpg

- id: doi:10.1088/1361-648X/ac5a24
  type: paper
  image: /images/publications/jpcm_special_issue_functionalisation.jpg

- id: doi:10.1021/acsnano.9b08943
  type: paper
  image: /images/publications/nn9b08943_0005.webp

- id: doi:10.1038/ncomms1574
  type: paper
  image: /images/publications/41467_2011_Article_BFncomms1574_Fig3_HTML.jpg.webp

- id: doi:10.1063/1.4884654
  type: paper
  image: /images/publications/253102_1_f3.jpeg
- id: doi:10.1021/nl048808v
  type: paper
  image: /images/publications/images_medium_nl048808vn00001.gif

- id: doi:10.1021/ja3026399
  type: paper
  image: /images/publications/images_medium_ja-2012-026399_0004.gif

- id: doi:10.1021/ja0719069
  type: paper
  image: /images/publications/images_medium_ja0719069n00001.gif

- id: doi:10.1103/PhysRevLett.93.226102
  type: paper
  image: /images/publications/PhysRevLett.93.226102.png

- id: doi:10.1103/PhysRevLett.100.246807
  type: paper
  image: /images/publications/PhysRevLett.100.246807.png

- id: doi:10.1126/sciadv.1602586  
  type: paper
  image: /images/publications/1602586-f1.jpeg

- id: doi:10.1021/acs.jpcc.9b04954
  type: paper
  image: /images/publications/images_medium_jp9b04954_0006.gif

- id: doi:10.1103/PhysRevB.97.155306
  type: paper
  image: /images/publications/PhysRevB.97.155306.png

- id:  doi:10.1016/j.apsusc.2017.11.058
  type: paper
  image: /images/publications/1-s2.0-S0169433217333019-gr1.jpg

- id: doi:10.1103/PhysRevB.95.075408
  type: paper
  image: /images/publications/PhysRevB.95.075408.png

- id: doi:10.1021/acs.jpcc.6b10485
  type: paper
  image: /images/publications/images_medium_jp-2016-104854_0008.gif

- id: doi:10.1103/PhysRevB.93.195304
  type: paper
  image: /images/publications/PhysRevB.93.195304.png

- id: doi:10.1063/1.4939124
  type: paper
  image: /images/publications/014705_1_f4.jpeg

- id: doi:10.1039/c6cp04328c
  type: paper
  image: /images/publications/c6cp04328c.jpeg

- id: doi:10.1021/acs.jpcc.5b01493
  type: paper
  image: /images/publications/images_medium_jp-2015-01493w_0011.gif

- id: doi:10.1088/0953-8984/27/5/054002
  type: paper
  image: /images/publications/cm501155f06_online.jpg

- id: doi:10.1021/nn3039484
  type: paper
  image: /images/publications/images_medium_nn-2012-039484_0006.gif

- id: doi:10.1021/jp311261r
  type: paper
  image: /images/publications/images_medium_jp-2012-11261r_0006.gif

- id: doi:10.1063/1.4772508
  type: paper
  image: /images/publications/m_012107_1_f1.jpeg


# - id: doi:10.1371/journal.pcbi.1007128
#   type: paper
#   description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
#   date: 2020-12-4
#   image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
#   buttons:
#     - type: manubot
#       link: https://greenelab.github.io/meta-review/
#     - type: source
#       text: Manuscript Source
#       link: https://github.com/greenelab/meta-review
#     - type: website
#       link: http://manubot.org/
#   tags:
#     - open science
#     - collaboration
#   repo: greenelab/meta-review

# - id: doi:10.1016/j.csbj.2020.05.017
#   image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg

# - id: doi:10.7554/eLife.32822
#   image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
